name: Deploy Development Server

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    
    steps:
      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  pull:
    runs-on: [self-hosted, linux, x64, ubuntu-server]
    steps:
      - name: Install updates
        run: sudo apt-get update

      - name: Pull TommyB13/Fitness-App-Project repository
        run: |
          git config pull.rebase false
          git remote set-url origin git@github.com:TommyB13/Fitness-App-Project.git
          git pull origin master
        working-directory: /home/ubuntu/Fitness-App-Project
#  start-web-server:
#    runs-on: [self-hosted, linux, x64, ubuntu-server]
#    steps:
#      - name: Start web server
#        run: 
